// lib/catalog.js — Phasal Bazar Real Catalog
// Prices: MRP = retail, wholesale = trade price

const store = {
  name:      "Phasal Bazar",
  upi_id:    "your-upi@bank",  // UPDATE THIS
  upi_name:  "Phasal Bazar",
  currency:  "INR",
};

const categories = [
  { id: "millets", emoji: "🌾", name: { en: "Millets & Rice", hi: "अनाज और चावल", ta: "தானியங்கள்", te: "చిరుధాన్యాలు" } },
  { id: "oils", emoji: "🫙", name: { en: "Oils & Ghee", hi: "तेल और घी", ta: "எண்ணெய் & நெய்", te: "నూనెలు & నెయ్యి" } },
  { id: "dals", emoji: "🫘", name: { en: "Dals & Pulses", hi: "दाल और दालें", ta: "பருப்பு வகைகள்", te: "పప్పులు" } },
  { id: "flours", emoji: "🌾", name: { en: "Flours & Primix", hi: "आटा और प्रीमिक्स", ta: "மாவு வகைகள்", te: "పిండి రకాలు" } },
  { id: "snacks", emoji: "🍪", name: { en: "Cookies & Snacks", hi: "कुकीज़ और नाश्ता", ta: "பிஸ்கட் & நாஷ்டா", te: "కుకీలు & స్నాక్స్" } },
  { id: "poha", emoji: "🍚", name: { en: "Poha", hi: "पोहा", ta: "அவல்", te: "అటుకులు" } },
  { id: "seeds", emoji: "🌱", name: { en: "Seeds & Superfoods", hi: "बीज और सुपरफूड", ta: "விதைகள்", te: "విత్తనాలు" } },
  { id: "spices", emoji: "🌶️", name: { en: "Spices & Condiments", hi: "मसाले", ta: "மசாலா வகைகள்", te: "మసాలాలు" } },
  { id: "sweets", emoji: "🍬", name: { en: "Natural Sweets", hi: "प्राकृतिक मिठाइयाँ", ta: "இயற்கை இனிப்பு", te: "సహజ తీపిలు" } },
  { id: "noodles", emoji: "🍜", name: { en: "Noodles & Pasta", hi: "नूडल्स और पास्ता", ta: "நூடுல்ஸ்", te: "నూడుల్స్" } },
];

const products = [
  {
    id: "OIL001", category: "oils", emoji: "🫙",
    name: { en: "Alsi Oil (250Ml)", hi: "Alsi Oil (250Ml)", ta: "Alsi Oil (250Ml)", te: "Alsi Oil (250Ml)" },
    desc: { en: "250ml | Natural & Pure", hi: "250ml | प्राकृतिक", ta: "250ml | இயற்கையானது", te: "250ml | సహజమైనది" },
    mrp: 135,
    wholesale: 120.12,
    unit: "250ml",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Groundnut_oil.jpg/320px-Groundnut_oil.jpg",
  },
  {
    id: "DAL001", category: "dals", emoji: "🫘",
    name: { en: "Arhar Dal (1Kg)", hi: "Arhar Dal (1Kg)", ta: "Arhar Dal (1Kg)", te: "Arhar Dal (1Kg)" },
    desc: { en: "1kg | Natural & Pure", hi: "1kg | प्राकृतिक", ta: "1kg | இயற்கையானது", te: "1kg | సహజమైనది" },
    mrp: 135,
    wholesale: 128.31,
    unit: "1kg",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pulses.jpg/320px-Pulses.jpg",
  },
  {
    id: "SWE001", category: "sweets", emoji: "🍬",
    name: { en: "Awala Candy Salti (100G)", hi: "Awala Candy Salti (100G)", ta: "Awala Candy Salti (100G)", te: "Awala Candy Salti (100G)" },
    desc: { en: "100gm | Natural & Pure", hi: "100gm | प्राकृतिक", ta: "100gm | இயற்கையானது", te: "100gm | సహజమైనది" },
    mrp: 45,
    wholesale: 40.27,
    unit: "100gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Honey_in_bowl.jpg/320px-Honey_in_bowl.jpg",
  },
  {
    id: "SWE002", category: "sweets", emoji: "🍬",
    name: { en: "Awala Mitha Candy (100G)", hi: "Awala Mitha Candy (100G)", ta: "Awala Mitha Candy (100G)", te: "Awala Mitha Candy (100G)" },
    desc: { en: "100gm | Natural & Pure", hi: "100gm | प्राकृतिक", ta: "100gm | இயற்கையானது", te: "100gm | సహజమైనది" },
    mrp: 45,
    wholesale: 41.63,
    unit: "100gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Honey_in_bowl.jpg/320px-Honey_in_bowl.jpg",
  },
  {
    id: "SWE003", category: "sweets", emoji: "🍬",
    name: { en: "Awla Masala  Candy (100G)", hi: "Awla Masala  Candy (100G)", ta: "Awla Masala  Candy (100G)", te: "Awla Masala  Candy (100G)" },
    desc: { en: "100gm | Natural & Pure", hi: "100gm | प्राकृतिक", ta: "100gm | இயற்கையானது", te: "100gm | సహజమైనది" },
    mrp: 45,
    wholesale: 38.9,
    unit: "100gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Honey_in_bowl.jpg/320px-Honey_in_bowl.jpg",
  },
  {
    id: "MIL001", category: "millets", emoji: "🌾",
    name: { en: "Bajra (1Kg)", hi: "Bajra (1Kg)", ta: "Bajra (1Kg)", te: "Bajra (1Kg)" },
    desc: { en: "1kg | Natural & Pure", hi: "1kg | प्राकृतिक", ta: "1kg | இயற்கையானது", te: "1kg | సహజమైనది" },
    mrp: 65,
    wholesale: 51.98,
    unit: "1kg",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "FLO001", category: "flours", emoji: "🌾",
    name: { en: "Bajra Aata (500G)", hi: "Bajra Aata (500G)", ta: "Bajra Aata (500G)", te: "Bajra Aata (500G)" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 40,
    wholesale: 32.08,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "SNA001", category: "snacks", emoji: "🍪",
    name: { en: "Bajra Cookies (150Gm)", hi: "Bajra Cookies (150Gm)", ta: "Bajra Cookies (150Gm)", te: "Bajra Cookies (150Gm)" },
    desc: { en: "150GM | Natural & Pure", hi: "150GM | प्राकृतिक", ta: "150GM | இயற்கையானது", te: "150GM | సహజమైనది" },
    mrp: 82,
    wholesale: 66.25,
    unit: "150GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cookies_on_a_plate.jpg/320px-Cookies_on_a_plate.jpg",
  },
  {
    id: "POH001", category: "poha", emoji: "🍚",
    name: { en: "Bajra Poha (250G)", hi: "Bajra Poha (250G)", ta: "Bajra Poha (250G)", te: "Bajra Poha (250G)" },
    desc: { en: "250gm | Natural & Pure", hi: "250gm | प्राकृतिक", ta: "250gm | இயற்கையானது", te: "250gm | సహజమైనది" },
    mrp: 51,
    wholesale: 41.82,
    unit: "250gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Poha.jpg/320px-Poha.jpg",
  },
  {
    id: "SNA002", category: "snacks", emoji: "🟤",
    name: { en: "Bijori Badi (200G)", hi: "Bijori Badi (200G)", ta: "Bijori Badi (200G)", te: "Bijori Badi (200G)" },
    desc: { en: "200gm | Natural & Pure", hi: "200gm | प्राकृतिक", ta: "200gm | இயற்கையானது", te: "200gm | సహజమైనది" },
    mrp: 110,
    wholesale: 88.33,
    unit: "200gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cookies_on_a_plate.jpg/320px-Cookies_on_a_plate.jpg",
  },
  {
    id: "MIL002", category: "millets", emoji: "🌾",
    name: { en: "Black Rice (1Kg)", hi: "Black Rice (1Kg)", ta: "Black Rice (1Kg)", te: "Black Rice (1Kg)" },
    desc: { en: "1kg | Natural & Pure", hi: "1kg | प्राकृतिक", ta: "1kg | இயற்கையானது", te: "1kg | సహజమైనది" },
    mrp: 190,
    wholesale: 153.35,
    unit: "1kg",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "MIL003", category: "millets", emoji: "🌾",
    name: { en: "Browntop (1Kg)", hi: "Browntop (1Kg)", ta: "Browntop (1Kg)", te: "Browntop (1Kg)" },
    desc: { en: "1kg | Natural & Pure", hi: "1kg | प्राकृतिक", ta: "1kg | இயற்கையானது", te: "1kg | సహజమైనది" },
    mrp: 254,
    wholesale: 205.02,
    unit: "1kg",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "MIL004", category: "millets", emoji: "🌾",
    name: { en: "Browntop (500G)", hi: "Browntop (500G)", ta: "Browntop (500G)", te: "Browntop (500G)" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 130,
    wholesale: 103.95,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "DAL002", category: "dals", emoji: "🫘",
    name: { en: "Chana Dal (500Gm)", hi: "Chana Dal (500Gm)", ta: "Chana Dal (500Gm)", te: "Chana Dal (500Gm)" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 80,
    wholesale: 70.98,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pulses.jpg/320px-Pulses.jpg",
  },
  {
    id: "FLO002", category: "flours", emoji: "🌾",
    name: { en: "Chawal Aata (1Kg)", hi: "Chawal Aata (1Kg)", ta: "Chawal Aata (1Kg)", te: "Chawal Aata (1Kg)" },
    desc: { en: "1kg | Natural & Pure", hi: "1kg | प्राकृतिक", ta: "1kg | இயற்கையானது", te: "1kg | సహజమైనది" },
    mrp: 52,
    wholesale: 46.41,
    unit: "1kg",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "SEE001", category: "seeds", emoji: "🌱",
    name: { en: "Chia Seed 100G", hi: "Chia Seed 100G", ta: "Chia Seed 100G", te: "Chia Seed 100G" },
    desc: { en: "100gm | Natural & Pure", hi: "100gm | प्राकृतिक", ta: "100gm | இயற்கையானது", te: "100gm | సహజమైనది" },
    mrp: 71,
    wholesale: 63.79,
    unit: "100gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Chia_seeds.jpg/320px-Chia_seeds.jpg",
  },
  {
    id: "MIL005", category: "millets", emoji: "🌾",
    name: { en: "Ragi (1Kg)", hi: "Ragi (1Kg)", ta: "Ragi (1Kg)", te: "Ragi (1Kg)" },
    desc: { en: "1KG | Natural & Pure", hi: "1KG | प्राकृतिक", ta: "1KG | இயற்கையானது", te: "1KG | సహజమైనది" },
    mrp: 95,
    wholesale: 75.63,
    unit: "1KG",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "FLO003", category: "flours", emoji: "🌾",
    name: { en: "Ragi Aata (500G)", hi: "Ragi Aata (500G)", ta: "Ragi Aata (500G)", te: "Ragi Aata (500G)" },
    desc: { en: "500GM | Natural & Pure", hi: "500GM | प्राकृतिक", ta: "500GM | இயற்கையானது", te: "500GM | సహజమైనది" },
    mrp: 53,
    wholesale: 42.36,
    unit: "500GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "SNA003", category: "snacks", emoji: "🍪",
    name: { en: "Coconut Cookies (150Gm)", hi: "Coconut Cookies (150Gm)", ta: "Coconut Cookies (150Gm)", te: "Coconut Cookies (150Gm)" },
    desc: { en: "150gm | Natural & Pure", hi: "150gm | प्राकृतिक", ta: "150gm | இயற்கையானது", te: "150gm | సహజమైనది" },
    mrp: 89,
    wholesale: 71.32,
    unit: "150gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cookies_on_a_plate.jpg/320px-Cookies_on_a_plate.jpg",
  },
  {
    id: "OIL002", category: "oils", emoji: "🫙",
    name: { en: "Coconut Oil (500Ml)", hi: "Coconut Oil (500Ml)", ta: "Coconut Oil (500Ml)", te: "Coconut Oil (500Ml)" },
    desc: { en: "500ml | Natural & Pure", hi: "500ml | प्राकृतिक", ta: "500ml | இயற்கையானது", te: "500ml | సహజమైనది" },
    mrp: 360,
    wholesale: 311.46,
    unit: "500ml",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Groundnut_oil.jpg/320px-Groundnut_oil.jpg",
  },
  {
    id: "OIL003", category: "oils", emoji: "🫙",
    name: { en: "Coconut Oil (1Lt)", hi: "Coconut Oil (1Lt)", ta: "Coconut Oil (1Lt)", te: "Coconut Oil (1Lt)" },
    desc: { en: "1LT | Natural & Pure", hi: "1LT | प्राकृतिक", ta: "1LT | இயற்கையானது", te: "1LT | సహజమైనది" },
    mrp: 696,
    wholesale: 609.13,
    unit: "1LT",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Groundnut_oil.jpg/320px-Groundnut_oil.jpg",
  },
  {
    id: "OIL004", category: "oils", emoji: "🧈",
    name: { en: "Deshi Ghee", hi: "Deshi Ghee", ta: "Deshi Ghee", te: "Deshi Ghee" },
    desc: { en: "250ml | Natural & Pure", hi: "250ml | प्राकृतिक", ta: "250ml | இயற்கையானது", te: "250ml | సహజమైనది" },
    mrp: 435,
    wholesale: 415.17,
    unit: "250ml",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Groundnut_oil.jpg/320px-Groundnut_oil.jpg",
  },
  {
    id: "SPI001", category: "spices", emoji: "🌶️",
    name: { en: "Dhaniya Powder (250G)", hi: "Dhaniya Powder (250G)", ta: "Dhaniya Powder (250G)", te: "Dhaniya Powder (250G)" },
    desc: { en: "250gm | Natural & Pure", hi: "250gm | प्राकृतिक", ta: "250gm | இயற்கையானது", te: "250gm | సహజమైనది" },
    mrp: 70,
    wholesale: 60.06,
    unit: "250gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Indian-spices.jpg/320px-Indian-spices.jpg",
  },
  {
    id: "MIL006", category: "millets", emoji: "🌾",
    name: { en: "Drk Rice (1Kg)", hi: "Drk Rice (1Kg)", ta: "Drk Rice (1Kg)", te: "Drk Rice (1Kg)" },
    desc: { en: "1kg | Natural & Pure", hi: "1kg | प्राकृतिक", ta: "1kg | இயற்கையானது", te: "1kg | సహజమైనది" },
    mrp: 90,
    wholesale: 81.27,
    unit: "1kg",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "MIL007", category: "millets", emoji: "🌾",
    name: { en: "Drk Rice (5Kg)", hi: "Drk Rice (5Kg)", ta: "Drk Rice (5Kg)", te: "Drk Rice (5Kg)" },
    desc: { en: "5kg | Natural & Pure", hi: "5kg | प्राकृतिक", ta: "5kg | இயற்கையானது", te: "5kg | సహజమైనది" },
    mrp: 340,
    wholesale: 332.06,
    unit: "5kg",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "SEE002", category: "seeds", emoji: "🌱",
    name: { en: "Flax Seed 100G", hi: "Flax Seed 100G", ta: "Flax Seed 100G", te: "Flax Seed 100G" },
    desc: { en: "100gm | Natural & Pure", hi: "100gm | प्राकृतिक", ta: "100gm | இயற்கையானது", te: "100gm | సహజమైనది" },
    mrp: 45,
    wholesale: 36.46,
    unit: "100gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Chia_seeds.jpg/320px-Chia_seeds.jpg",
  },
  {
    id: "MIL008", category: "millets", emoji: "🌾",
    name: { en: "Foxtail (1Kg)", hi: "Foxtail (1Kg)", ta: "Foxtail (1Kg)", te: "Foxtail (1Kg)" },
    desc: { en: "1kg | Natural & Pure", hi: "1kg | प्राकृतिक", ta: "1kg | இயற்கையானது", te: "1kg | సహజమైనది" },
    mrp: 145,
    wholesale: 118.34,
    unit: "1kg",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "MIL009", category: "millets", emoji: "🌾",
    name: { en: "Foxtail (500G)", hi: "Foxtail (500G)", ta: "Foxtail (500G)", te: "Foxtail (500G)" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 85,
    wholesale: 68.14,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "FLO004", category: "flours", emoji: "🌾",
    name: { en: "Foxtail Aata (500G)", hi: "Foxtail Aata (500G)", ta: "Foxtail Aata (500G)", te: "Foxtail Aata (500G)" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 89,
    wholesale: 71.7,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "SNA004", category: "snacks", emoji: "🍪",
    name: { en: "Foxtail Cookies (150Gm)", hi: "Foxtail Cookies (150Gm)", ta: "Foxtail Cookies (150Gm)", te: "Foxtail Cookies (150Gm)" },
    desc: { en: "150GM | Natural & Pure", hi: "150GM | प्राकृतिक", ta: "150GM | இயற்கையானது", te: "150GM | సహజమైనది" },
    mrp: 87,
    wholesale: 70.37,
    unit: "150GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cookies_on_a_plate.jpg/320px-Cookies_on_a_plate.jpg",
  },
  {
    id: "SNA005", category: "snacks", emoji: "🍪",
    name: { en: "Foxtail Cookies Salti (150Gm)", hi: "Foxtail Cookies Salti (150Gm)", ta: "Foxtail Cookies Salti (150Gm)", te: "Foxtail Cookies Salti (150Gm)" },
    desc: { en: "150GM | Natural & Pure", hi: "150GM | प्राकृतिक", ta: "150GM | இயற்கையானது", te: "150GM | సహజమైనది" },
    mrp: 87,
    wholesale: 70.37,
    unit: "150GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cookies_on_a_plate.jpg/320px-Cookies_on_a_plate.jpg",
  },
  {
    id: "POH002", category: "poha", emoji: "🍚",
    name: { en: "Foxtail Poha (250G)", hi: "Foxtail Poha (250G)", ta: "Foxtail Poha (250G)", te: "Foxtail Poha (250G)" },
    desc: { en: "250gm | Natural & Pure", hi: "250gm | प्राकृतिक", ta: "250gm | இயற்கையானது", te: "250gm | సహజమైనది" },
    mrp: 70,
    wholesale: 55.86,
    unit: "250gm",
    stock: 100,
    image_url: "https://5.imimg.com/data5/SELLER/Default/2023/1/AN/SQ/XL/5477230/rice-flakes-rice-flaks-phoha-1000x1000.jpg",
  },
  {
    id: "DAL003", category: "dals", emoji: "🫘",
    name: { en: "Futa Chana 250G", hi: "Futa Chana 250G", ta: "Futa Chana 250G", te: "Futa Chana 250G" },
    desc: { en: "250gm | Natural & Pure", hi: "250gm | प्राकृतिक", ta: "250gm | இயற்கையானது", te: "250gm | సహజమైనది" },
    mrp: 50,
    wholesale: 41.89,
    unit: "250gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pulses.jpg/320px-Pulses.jpg",
  },
  {
    id: "OIL005", category: "oils", emoji: "🫙",
    name: { en: "Groundnut Oil (1Lt)", hi: "Groundnut Oil (1Lt)", ta: "Groundnut Oil (1Lt)", te: "Groundnut Oil (1Lt)" },
    desc: { en: "1LT | Natural & Pure", hi: "1LT | प्राकृतिक", ta: "1LT | இயற்கையானது", te: "1LT | సహజమైనది" },
    mrp: 330,
    wholesale: 287.62,
    unit: "1LT",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Groundnut_oil.jpg/320px-Groundnut_oil.jpg",
  },
  {
    id: "SWE004", category: "sweets", emoji: "🍬",
    name: { en: "Gud Powder 500G", hi: "Gud Powder 500G", ta: "Gud Powder 500G", te: "Gud Powder 500G" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 120,
    wholesale: 63.73,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Honey_in_bowl.jpg/320px-Honey_in_bowl.jpg",
  },
  {
    id: "SPI002", category: "spices", emoji: "🌶️",
    name: { en: "Haldi Powder (250G)", hi: "Haldi Powder (250G)", ta: "Haldi Powder (250G)", te: "Haldi Powder (250G)" },
    desc: { en: "250gm | Natural & Pure", hi: "250gm | प्राकृतिक", ta: "250gm | இயற்கையானது", te: "250gm | సహజమైనది" },
    mrp: 90,
    wholesale: 80.8,
    unit: "250gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Indian-spices.jpg/320px-Indian-spices.jpg",
  },
  {
    id: "SWE005", category: "sweets", emoji: "🍯",
    name: { en: "Deshi Honey (250G)", hi: "Deshi Honey (250G)", ta: "Deshi Honey (250G)", te: "Deshi Honey (250G)" },
    desc: { en: "250gm | Natural & Pure", hi: "250gm | प्राकृतिक", ta: "250gm | இயற்கையானது", te: "250gm | సహజమైనది" },
    mrp: 135,
    wholesale: 122.62,
    unit: "250gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Honey_in_bowl.jpg/320px-Honey_in_bowl.jpg",
  },
  {
    id: "FLO005", category: "flours", emoji: "🌾",
    name: { en: "Jau Aata (500G)", hi: "Jau Aata (500G)", ta: "Jau Aata (500G)", te: "Jau Aata (500G)" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 55,
    wholesale: 44.13,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "MIL010", category: "millets", emoji: "🌾",
    name: { en: "Jowar (1Kg)", hi: "Jowar (1Kg)", ta: "Jowar (1Kg)", te: "Jowar (1Kg)" },
    desc: { en: "1KG | Natural & Pure", hi: "1KG | प्राकृतिक", ta: "1KG | இயற்கையானது", te: "1KG | సహజమైనది" },
    mrp: 68,
    wholesale: 54.34,
    unit: "1KG",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "FLO006", category: "flours", emoji: "🌾",
    name: { en: "Jowar Aata (500G)", hi: "Jowar Aata (500G)", ta: "Jowar Aata (500G)", te: "Jowar Aata (500G)" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 42,
    wholesale: 33.39,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "SWE006", category: "sweets", emoji: "🍯",
    name: { en: "Deshi Honey (500G)", hi: "Deshi Honey (500G)", ta: "Deshi Honey (500G)", te: "Deshi Honey (500G)" },
    desc: { en: "500GM | Natural & Pure", hi: "500GM | प्राकृतिक", ta: "500GM | இயற்கையானது", te: "500GM | సహజమైనది" },
    mrp: 240,
    wholesale: 234.32,
    unit: "500GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Honey_in_bowl.jpg/320px-Honey_in_bowl.jpg",
  },
  {
    id: "POH003", category: "poha", emoji: "🍚",
    name: { en: "Jowar Poha (250G)", hi: "Jowar Poha (250G)", ta: "Jowar Poha (250G)", te: "Jowar Poha (250G)" },
    desc: { en: "250gm | Natural & Pure", hi: "250gm | प्राकृतिक", ta: "250gm | இயற்கையானது", te: "250gm | సహజమైనది" },
    mrp: 55,
    wholesale: 46.6,
    unit: "250gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Poha.jpg/320px-Poha.jpg",
  },
  {
    id: "FLO007", category: "flours", emoji: "🌾",
    name: { en: "Kodo Aata (500G)", hi: "Kodo Aata (500G)", ta: "Kodo Aata (500G)", te: "Kodo Aata (500G)" },
    desc: { en: "500GM | Natural & Pure", hi: "500GM | प्राकृतिक", ta: "500GM | இயற்கையானது", te: "500GM | సహజమైనది" },
    mrp: 78,
    wholesale: 62.4,
    unit: "500GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "SNA006", category: "snacks", emoji: "🍪",
    name: { en: "Kodo Cookies (150G)", hi: "Kodo Cookies (150G)", ta: "Kodo Cookies (150G)", te: "Kodo Cookies (150G)" },
    desc: { en: "150GM | Natural & Pure", hi: "150GM | प्राकृतिक", ta: "150GM | இயற்கையானது", te: "150GM | సహజమైనది" },
    mrp: 90,
    wholesale: 72.69,
    unit: "150GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cookies_on_a_plate.jpg/320px-Cookies_on_a_plate.jpg",
  },
  {
    id: "MIL011", category: "millets", emoji: "🌾",
    name: { en: "Kodo Rice (1Kg)", hi: "Kodo Rice (1Kg)", ta: "Kodo Rice (1Kg)", te: "Kodo Rice (1Kg)" },
    desc: { en: "1kg | Natural & Pure", hi: "1kg | प्राकृतिक", ta: "1kg | இயற்கையானது", te: "1kg | సహజమైనది" },
    mrp: 125,
    wholesale: 102.64,
    unit: "1kg",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "MIL012", category: "millets", emoji: "🌾",
    name: { en: "Kodo Rice (500G)", hi: "Kodo Rice (500G)", ta: "Kodo Rice (500G)", te: "Kodo Rice (500G)" },
    desc: { en: "500GM | Natural & Pure", hi: "500GM | प्राकृतिक", ta: "500GM | இயற்கையானது", te: "500GM | సహజమైనది" },
    mrp: 75,
    wholesale: 49.88,
    unit: "500GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "FLO008", category: "flours", emoji: "🌾",
    name: { en: "Kutki Aata (500G)", hi: "Kutki Aata (500G)", ta: "Kutki Aata (500G)", te: "Kutki Aata (500G)" },
    desc: { en: "500GM | Natural & Pure", hi: "500GM | प्राकृतिक", ta: "500GM | இயற்கையானது", te: "500GM | సహజమైనది" },
    mrp: 98,
    wholesale: 79.38,
    unit: "500GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "POH004", category: "poha", emoji: "🍚",
    name: { en: "Kutki Poha (250G)", hi: "Kutki Poha (250G)", ta: "Kutki Poha (250G)", te: "Kutki Poha (250G)" },
    desc: { en: "250GM | Natural & Pure", hi: "250GM | प्राकृतिक", ta: "250GM | இயற்கையானது", te: "250GM | సహజమైనది" },
    mrp: 75,
    wholesale: 59.03,
    unit: "250GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Poha.jpg/320px-Poha.jpg",
  },
  {
    id: "MIL013", category: "millets", emoji: "🌾",
    name: { en: "Kutki Rice (1Kg)", hi: "Kutki Rice (1Kg)", ta: "Kutki Rice (1Kg)", te: "Kutki Rice (1Kg)" },
    desc: { en: "1KG | Natural & Pure", hi: "1KG | प्राकृतिक", ta: "1KG | இயற்கையானது", te: "1KG | సహజమైనది" },
    mrp: 160,
    wholesale: 130.59,
    unit: "1KG",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "MIL014", category: "millets", emoji: "🌾",
    name: { en: "Kutki Rice (500G)", hi: "Kutki Rice (500G)", ta: "Kutki Rice (500G)", te: "Kutki Rice (500G)" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 85,
    wholesale: 70.09,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "FLO009", category: "flours", emoji: "🌾",
    name: { en: "Makka Aata 500G", hi: "Makka Aata 500G", ta: "Makka Aata 500G", te: "Makka Aata 500G" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 42,
    wholesale: 33.42,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "SEE003", category: "seeds", emoji: "🌱",
    name: { en: "Moringa Powder (100G)", hi: "Moringa Powder (100G)", ta: "Moringa Powder (100G)", te: "Moringa Powder (100G)" },
    desc: { en: "100gm | Natural & Pure", hi: "100gm | प्राकृतिक", ta: "100gm | இயற்கையானது", te: "100gm | సహజమైనది" },
    mrp: 98,
    wholesale: 78.75,
    unit: "100gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Chia_seeds.jpg/320px-Chia_seeds.jpg",
  },
  {
    id: "FLO010", category: "flours", emoji: "🌾",
    name: { en: "Multi Grain Aata (1Kg)", hi: "Multi Grain Aata (1Kg)", ta: "Multi Grain Aata (1Kg)", te: "Multi Grain Aata (1Kg)" },
    desc: { en: "1KG | Natural & Pure", hi: "1KG | प्राकृतिक", ta: "1KG | இயற்கையானது", te: "1KG | సహజమైనది" },
    mrp: 100,
    wholesale: 80.99,
    unit: "1KG",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "NOO001", category: "noodles", emoji: "🍜",
    name: { en: "Multi Millert Noodles (175G)", hi: "Multi Millert Noodles (175G)", ta: "Multi Millert Noodles (175G)", te: "Multi Millert Noodles (175G)" },
    desc: { en: "175GM | Natural & Pure", hi: "175GM | प्राकृतिक", ta: "175GM | இயற்கையானது", te: "175GM | సహజమైనది" },
    mrp: 85,
    wholesale: 59.31,
    unit: "175GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Ramen_noodles.jpg/320px-Ramen_noodles.jpg",
  },
  {
    id: "NOO002", category: "noodles", emoji: "🍜",
    name: { en: "Multi Millet Pasta (175G)", hi: "Multi Millet Pasta (175G)", ta: "Multi Millet Pasta (175G)", te: "Multi Millet Pasta (175G)" },
    desc: { en: "175GM | Natural & Pure", hi: "175GM | प्राकृतिक", ta: "175GM | இயற்கையானது", te: "175GM | సహజమైనది" },
    mrp: 85,
    wholesale: 56.58,
    unit: "175GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Ramen_noodles.jpg/320px-Ramen_noodles.jpg",
  },
  {
    id: "OIL006", category: "oils", emoji: "🫙",
    name: { en: "Musterd Oil 1 Lt", hi: "Musterd Oil 1 Lt", ta: "Musterd Oil 1 Lt", te: "Musterd Oil 1 Lt" },
    desc: { en: "1LT | Natural & Pure", hi: "1LT | प्राकृतिक", ta: "1LT | இயற்கையானது", te: "1LT | సహజమైనది" },
    mrp: 325,
    wholesale: 284.44,
    unit: "1LT",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Groundnut_oil.jpg/320px-Groundnut_oil.jpg",
  },
  {
    id: "SNA007", category: "snacks", emoji: "🍪",
    name: { en: "Oats Cookies  (150G)", hi: "Oats Cookies  (150G)", ta: "Oats Cookies  (150G)", te: "Oats Cookies  (150G)" },
    desc: { en: "150GM | Natural & Pure", hi: "150GM | प्राकृतिक", ta: "150GM | இயற்கையானது", te: "150GM | సహజమైనది" },
    mrp: 120,
    wholesale: 96.81,
    unit: "150GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cookies_on_a_plate.jpg/320px-Cookies_on_a_plate.jpg",
  },
  {
    id: "MIL015", category: "millets", emoji: "🌾",
    name: { en: "Proso Millet (1Kg)", hi: "Proso Millet (1Kg)", ta: "Proso Millet (1Kg)", te: "Proso Millet (1Kg)" },
    desc: { en: "1kg | Natural & Pure", hi: "1kg | प्राकृतिक", ta: "1kg | இயற்கையானது", te: "1kg | సహజమైనది" },
    mrp: 170,
    wholesale: 138.82,
    unit: "1kg",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "MIL016", category: "millets", emoji: "🌾",
    name: { en: "Quinoa 500G", hi: "Quinoa 500G", ta: "Quinoa 500G", te: "Quinoa 500G" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 110,
    wholesale: 86.82,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "FLO011", category: "flours", emoji: "🌾",
    name: { en: "Ragi Chila Primix (300Gm)", hi: "Ragi Chila Primix (300Gm)", ta: "Ragi Chila Primix (300Gm)", te: "Ragi Chila Primix (300Gm)" },
    desc: { en: "300GM | Natural & Pure", hi: "300GM | प्राकृतिक", ta: "300GM | இயற்கையானது", te: "300GM | సహజమైనది" },
    mrp: 60,
    wholesale: 50.23,
    unit: "300GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "FLO012", category: "flours", emoji: "🌾",
    name: { en: "Ragi Chila Primix (500Gm)", hi: "Ragi Chila Primix (500Gm)", ta: "Ragi Chila Primix (500Gm)", te: "Ragi Chila Primix (500Gm)" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 85,
    wholesale: 75.42,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "SNA008", category: "snacks", emoji: "🍪",
    name: { en: "Ragi Cookies (150G)", hi: "Ragi Cookies (150G)", ta: "Ragi Cookies (150G)", te: "Ragi Cookies (150G)" },
    desc: { en: "150GM | Natural & Pure", hi: "150GM | प्राकृतिक", ta: "150GM | இயற்கையானது", te: "150GM | సహజమైనది" },
    mrp: 76,
    wholesale: 61.22,
    unit: "150GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cookies_on_a_plate.jpg/320px-Cookies_on_a_plate.jpg",
  },
  {
    id: "SNA009", category: "snacks", emoji: "🍪",
    name: { en: "Ragi Cookies Salti (150G)", hi: "Ragi Cookies Salti (150G)", ta: "Ragi Cookies Salti (150G)", te: "Ragi Cookies Salti (150G)" },
    desc: { en: "150GM | Natural & Pure", hi: "150GM | प्राकृतिक", ta: "150GM | இயற்கையானது", te: "150GM | సహజమైనది" },
    mrp: 76,
    wholesale: 61.22,
    unit: "150GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cookies_on_a_plate.jpg/320px-Cookies_on_a_plate.jpg",
  },
  {
    id: "POH005", category: "poha", emoji: "🍚",
    name: { en: "Ragi Poha (250G)", hi: "Ragi Poha (250G)", ta: "Ragi Poha (250G)", te: "Ragi Poha (250G)" },
    desc: { en: "250gm | Natural & Pure", hi: "250gm | प्राकृतिक", ta: "250gm | இயற்கையானது", te: "250gm | సహజమైనది" },
    mrp: 55,
    wholesale: 42.19,
    unit: "250gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Poha.jpg/320px-Poha.jpg",
  },
  {
    id: "MIL017", category: "millets", emoji: "🌾",
    name: { en: "Sanwa (1Kg)", hi: "Sanwa (1Kg)", ta: "Sanwa (1Kg)", te: "Sanwa (1Kg)" },
    desc: { en: "1 kg | Natural & Pure", hi: "1 kg | प्राकृतिक", ta: "1 kg | இயற்கையானது", te: "1 kg | సహజమైనది" },
    mrp: 145,
    wholesale: 117.06,
    unit: "1 kg",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "MIL018", category: "millets", emoji: "🌾",
    name: { en: "Sanwa (500G)", hi: "Sanwa (500G)", ta: "Sanwa (500G)", te: "Sanwa (500G)" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 75,
    wholesale: 58.55,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "FLO013", category: "flours", emoji: "🌾",
    name: { en: "Sanwa Aata (500G)", hi: "Sanwa Aata (500G)", ta: "Sanwa Aata (500G)", te: "Sanwa Aata (500G)" },
    desc: { en: "500gm | Natural & Pure", hi: "500gm | प्राकृतिक", ta: "500gm | இயற்கையானது", te: "500gm | సహజమైనది" },
    mrp: 82,
    wholesale: 65.66,
    unit: "500gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "POH006", category: "poha", emoji: "🍚",
    name: { en: "Sanwa Poha (250G)", hi: "Sanwa Poha (250G)", ta: "Sanwa Poha (250G)", te: "Sanwa Poha (250G)" },
    desc: { en: "250gm | Natural & Pure", hi: "250gm | प्राकृतिक", ta: "250gm | இயற்கையானது", te: "250gm | సహజమైనది" },
    mrp: 80,
    wholesale: 62.3,
    unit: "250gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Poha.jpg/320px-Poha.jpg",
  },
  {
    id: "OIL007", category: "oils", emoji: "🫙",
    name: { en: "Sunflower Oil (1Lt)", hi: "Sunflower Oil (1Lt)", ta: "Sunflower Oil (1Lt)", te: "Sunflower Oil (1Lt)" },
    desc: { en: "1LT | Natural & Pure", hi: "1LT | प्राकृतिक", ta: "1LT | இயற்கையானது", te: "1LT | సహజమైనది" },
    mrp: 350,
    wholesale: 306.5,
    unit: "1LT",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Groundnut_oil.jpg/320px-Groundnut_oil.jpg",
  },
  {
    id: "OIL008", category: "oils", emoji: "🫙",
    name: { en: "Til Oil (250Ml)", hi: "Til Oil (250Ml)", ta: "Til Oil (250Ml)", te: "Til Oil (250Ml)" },
    desc: { en: "250ml | Natural & Pure", hi: "250ml | प्राकृतिक", ta: "250ml | இயற்கையானது", te: "250ml | సహజమైనది" },
    mrp: 140,
    wholesale: 124.42,
    unit: "250ml",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Groundnut_oil.jpg/320px-Groundnut_oil.jpg",
  },
  {
    id: "MIL019", category: "millets", emoji: "🌾",
    name: { en: "Brown Rice", hi: "Brown Rice", ta: "Brown Rice", te: "Brown Rice" },
    desc: { en: "1KG | Natural & Pure", hi: "1KG | प्राकृतिक", ta: "1KG | இயற்கையானது", te: "1KG | సహజమైనది" },
    mrp: 125,
    wholesale: 101.93,
    unit: "1KG",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "OIL009", category: "oils", emoji: "🫙",
    name: { en: "Cocont Oil (250Ml)", hi: "Cocont Oil (250Ml)", ta: "Cocont Oil (250Ml)", te: "Cocont Oil (250Ml)" },
    desc: { en: "250ML | Natural & Pure", hi: "250ML | प्राकृतिक", ta: "250ML | இயற்கையானது", te: "250ML | సహజమైనది" },
    mrp: 199,
    wholesale: 159.26,
    unit: "250ML",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Groundnut_oil.jpg/320px-Groundnut_oil.jpg",
  },
  {
    id: "OIL010", category: "oils", emoji: "🫙",
    name: { en: "Groundnut Oil (500Ml)", hi: "Groundnut Oil (500Ml)", ta: "Groundnut Oil (500Ml)", te: "Groundnut Oil (500Ml)" },
    desc: { en: "500ML | Natural & Pure", hi: "500ML | प्राकृतिक", ta: "500ML | இயற்கையானது", te: "500ML | సహజమైనది" },
    mrp: 165,
    wholesale: 143.32,
    unit: "500ML",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Groundnut_oil.jpg/320px-Groundnut_oil.jpg",
  },
  {
    id: "OIL011", category: "oils", emoji: "🫙",
    name: { en: "Mustured Oil (500 Ml)", hi: "Mustured Oil (500 Ml)", ta: "Mustured Oil (500 Ml)", te: "Mustured Oil (500 Ml)" },
    desc: { en: "500ML | Natural & Pure", hi: "500ML | प्राकृतिक", ta: "500ML | இயற்கையானது", te: "500ML | సహజమైనది" },
    mrp: 165,
    wholesale: 143.32,
    unit: "500ML",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Groundnut_oil.jpg/320px-Groundnut_oil.jpg",
  },
  {
    id: "FLO014", category: "flours", emoji: "🌾",
    name: { en: "Kuttu Aata (250Gm)", hi: "Kuttu Aata (250Gm)", ta: "Kuttu Aata (250Gm)", te: "Kuttu Aata (250Gm)" },
    desc: { en: "250GM | Natural & Pure", hi: "250GM | प्राकृतिक", ta: "250GM | இயற்கையானது", te: "250GM | సహజమైనది" },
    mrp: 70,
    wholesale: 56.6,
    unit: "250GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Whole_wheat_flour.jpg/320px-Whole_wheat_flour.jpg",
  },
  {
    id: "SWE007", category: "sweets", emoji: "🍬",
    name: { en: "Khand (800G)", hi: "Khand (800G)", ta: "Khand (800G)", te: "Khand (800G)" },
    desc: { en: "800gm | Natural & Pure", hi: "800gm | प्राकृतिक", ta: "800gm | இயற்கையானது", te: "800gm | సహజమైనది" },
    mrp: 98,
    wholesale: 78.79,
    unit: "800gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Honey_in_bowl.jpg/320px-Honey_in_bowl.jpg",
  },
  {
    id: "SNA010", category: "snacks", emoji: "🟤",
    name: { en: "Lai Badi (200G)", hi: "Lai Badi (200G)", ta: "Lai Badi (200G)", te: "Lai Badi (200G)" },
    desc: { en: "200gm | Natural & Pure", hi: "200gm | प्राकृतिक", ta: "200gm | இயற்கையானது", te: "200gm | సహజమైనది" },
    mrp: 99,
    wholesale: 78.75,
    unit: "200gm",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cookies_on_a_plate.jpg/320px-Cookies_on_a_plate.jpg",
  },
  {
    id: "SPI003", category: "spices", emoji: "🌶️",
    name: { en: "Mirch Powder", hi: "Mirch Powder", ta: "Mirch Powder", te: "Mirch Powder" },
    desc: { en: "250 GM | Natural & Pure", hi: "250 GM | प्राकृतिक", ta: "250 GM | இயற்கையானது", te: "250 GM | సహజమైనది" },
    mrp: 110,
    wholesale: 90.09,
    unit: "250 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Indian-spices.jpg/320px-Indian-spices.jpg",
  },
  {
    id: "DAL004", category: "dals", emoji: "🫘",
    name: { en: "Chilka Moog Dall (500Gm)", hi: "Chilka Moog Dall (500Gm)", ta: "Chilka Moog Dall (500Gm)", te: "Chilka Moog Dall (500Gm)" },
    desc: { en: "500 GM | Natural & Pure", hi: "500 GM | प्राकृतिक", ta: "500 GM | இயற்கையானது", te: "500 GM | సహజమైనది" },
    mrp: 75,
    wholesale: 66.15,
    unit: "500 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pulses.jpg/320px-Pulses.jpg",
  },
  {
    id: "DAL005", category: "dals", emoji: "🫘",
    name: { en: "Moong Khada (1Kg)", hi: "Moong Khada (1Kg)", ta: "Moong Khada (1Kg)", te: "Moong Khada (1Kg)" },
    desc: { en: "1KG | Natural & Pure", hi: "1KG | प्राकृतिक", ta: "1KG | இயற்கையானது", te: "1KG | సహజమైనది" },
    mrp: 110,
    wholesale: 108.14,
    unit: "1KG",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pulses.jpg/320px-Pulses.jpg",
  },
  {
    id: "SEE004", category: "seeds", emoji: "🌱",
    name: { en: "Pumkin Seed 100G", hi: "Pumkin Seed 100G", ta: "Pumkin Seed 100G", te: "Pumkin Seed 100G" },
    desc: { en: "100 GM | Natural & Pure", hi: "100 GM | प्राकृतिक", ta: "100 GM | இயற்கையானது", te: "100 GM | సహజమైనది" },
    mrp: 75,
    wholesale: 58.91,
    unit: "100 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Chia_seeds.jpg/320px-Chia_seeds.jpg",
  },
  {
    id: "SNA011", category: "snacks", emoji: "🟤",
    name: { en: "Rakhiya Badi (200G)", hi: "Rakhiya Badi (200G)", ta: "Rakhiya Badi (200G)", te: "Rakhiya Badi (200G)" },
    desc: { en: "200 GM | Natural & Pure", hi: "200 GM | प्राकृतिक", ta: "200 GM | இயற்கையானது", te: "200 GM | సహజమైనది" },
    mrp: 102,
    wholesale: 81.85,
    unit: "200 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cookies_on_a_plate.jpg/320px-Cookies_on_a_plate.jpg",
  },
  {
    id: "MIL020", category: "millets", emoji: "🌾",
    name: { en: "Red Rice (1Kg)", hi: "Red Rice (1Kg)", ta: "Red Rice (1Kg)", te: "Red Rice (1Kg)" },
    desc: { en: "1 kg | Natural & Pure", hi: "1 kg | प्राकृतिक", ta: "1 kg | இயற்கையானது", te: "1 kg | సహజమైనది" },
    mrp: 126,
    wholesale: 102.29,
    unit: "1 kg",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ragi_finger_millet.jpg/320px-Ragi_finger_millet.jpg",
  },
  {
    id: "SWE008", category: "sweets", emoji: "🍬",
    name: { en: "Sabudana (500Gm)", hi: "Sabudana (500Gm)", ta: "Sabudana (500Gm)", te: "Sabudana (500Gm)" },
    desc: { en: "500 GM | Natural & Pure", hi: "500 GM | प्राकृतिक", ta: "500 GM | இயற்கையானது", te: "500 GM | సహజమైనది" },
    mrp: 55,
    wholesale: 48.51,
    unit: "500 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Honey_in_bowl.jpg/320px-Honey_in_bowl.jpg",
  },
  {
    id: "SEE005", category: "seeds", emoji: "🌱",
    name: { en: "Sunflower Seed (100Gm)", hi: "Sunflower Seed (100Gm)", ta: "Sunflower Seed (100Gm)", te: "Sunflower Seed (100Gm)" },
    desc: { en: "100 GM | Natural & Pure", hi: "100 GM | प्राकृतिक", ta: "100 GM | இயற்கையானது", te: "100 GM | సహజమైనది" },
    mrp: 46,
    wholesale: 37.17,
    unit: "100 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Chia_seeds.jpg/320px-Chia_seeds.jpg",
  },
  {
    id: "DAL006", category: "dals", emoji: "🫘",
    name: { en: "Urad Dal (500Gm)", hi: "Urad Dal (500Gm)", ta: "Urad Dal (500Gm)", te: "Urad Dal (500Gm)" },
    desc: { en: "500 GM | Natural & Pure", hi: "500 GM | प्राकृतिक", ta: "500 GM | இயற்கையானது", te: "500 GM | సహజమైనది" },
    mrp: 85,
    wholesale: 80.01,
    unit: "500 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pulses.jpg/320px-Pulses.jpg",
  },
  {
    id: "DAL007", category: "dals", emoji: "🫘",
    name: { en: "Rajmaa (500Gm)", hi: "Rajmaa (500Gm)", ta: "Rajmaa (500Gm)", te: "Rajmaa (500Gm)" },
    desc: { en: "500 GM | Natural & Pure", hi: "500 GM | प्राकृतिक", ta: "500 GM | இயற்கையானது", te: "500 GM | సహజమైనది" },
    mrp: 85,
    wholesale: 78.75,
    unit: "500 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pulses.jpg/320px-Pulses.jpg",
  },
  {
    id: "DAL008", category: "dals", emoji: "🫘",
    name: { en: "Desi Chana (500Gm)", hi: "Desi Chana (500Gm)", ta: "Desi Chana (500Gm)", te: "Desi Chana (500Gm)" },
    desc: { en: "500 GM | Natural & Pure", hi: "500 GM | प्राकृतिक", ta: "500 GM | இயற்கையானது", te: "500 GM | సహజమైనది" },
    mrp: 60,
    wholesale: 49.14,
    unit: "500 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pulses.jpg/320px-Pulses.jpg",
  },
  {
    id: "DAL009", category: "dals", emoji: "🫘",
    name: { en: "Jhurga (500Gm)", hi: "Jhurga (500Gm)", ta: "Jhurga (500Gm)", te: "Jhurga (500Gm)" },
    desc: { en: "500 GM | Natural & Pure", hi: "500 GM | प्राकृतिक", ta: "500 GM | இயற்கையானது", te: "500 GM | సహజమైనది" },
    mrp: 65,
    wholesale: 59.85,
    unit: "500 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pulses.jpg/320px-Pulses.jpg",
  },
  {
    id: "DAL010", category: "dals", emoji: "🫘",
    name: { en: "Green Matter (500Gm)", hi: "Green Matter (500Gm)", ta: "Green Matter (500Gm)", te: "Green Matter (500Gm)" },
    desc: { en: "500 GM | Natural & Pure", hi: "500 GM | प्राकृतिक", ta: "500 GM | இயற்கையானது", te: "500 GM | సహజమైనది" },
    mrp: 50,
    wholesale: 44.1,
    unit: "500 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pulses.jpg/320px-Pulses.jpg",
  },
  {
    id: "DAL011", category: "dals", emoji: "🫘",
    name: { en: "Kabuli Chana (500Gm)", hi: "Kabuli Chana (500Gm)", ta: "Kabuli Chana (500Gm)", te: "Kabuli Chana (500Gm)" },
    desc: { en: "500 GM | Natural & Pure", hi: "500 GM | प्राकृतिक", ta: "500 GM | இயற்கையானது", te: "500 GM | సహజమైనది" },
    mrp: 80,
    wholesale: 73.71,
    unit: "500 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pulses.jpg/320px-Pulses.jpg",
  },
  {
    id: "DAL012", category: "dals", emoji: "🫘",
    name: { en: "Moong Dall 500G", hi: "Moong Dall 500G", ta: "Moong Dall 500G", te: "Moong Dall 500G" },
    desc: { en: "500 GM | Natural & Pure", hi: "500 GM | प्राकृतिक", ta: "500 GM | இயற்கையானது", te: "500 GM | సహజమైనది" },
    mrp: 80,
    wholesale: 75.28,
    unit: "500 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pulses.jpg/320px-Pulses.jpg",
  },
  {
    id: "SEE006", category: "seeds", emoji: "🌱",
    name: { en: "Sarson Seed (200 Gm)", hi: "Sarson Seed (200 Gm)", ta: "Sarson Seed (200 Gm)", te: "Sarson Seed (200 Gm)" },
    desc: { en: "200 GM | Natural & Pure", hi: "200 GM | प्राकृतिक", ta: "200 GM | இயற்கையானது", te: "200 GM | సహజమైనది" },
    mrp: 35,
    wholesale: 26.33,
    unit: "200 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Chia_seeds.jpg/320px-Chia_seeds.jpg",
  },
  {
    id: "SPI004", category: "spices", emoji: "🌶️",
    name: { en: "Jeera (100 Gm)", hi: "Jeera (100 Gm)", ta: "Jeera (100 Gm)", te: "Jeera (100 Gm)" },
    desc: { en: "100 GM | Natural & Pure", hi: "100 GM | प्राकृतिक", ta: "100 GM | இயற்கையானது", te: "100 GM | సహజమైనది" },
    mrp: 45,
    wholesale: 34.52,
    unit: "100 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Indian-spices.jpg/320px-Indian-spices.jpg",
  },
  {
    id: "SPI005", category: "spices", emoji: "🌶️",
    name: { en: "White Till (100Gm)", hi: "White Till (100Gm)", ta: "White Till (100Gm)", te: "White Till (100Gm)" },
    desc: { en: "100 GM | Natural & Pure", hi: "100 GM | प्राकृतिक", ta: "100 GM | இயற்கையானது", te: "100 GM | సహజమైనది" },
    mrp: 40,
    wholesale: 29.89,
    unit: "100 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Indian-spices.jpg/320px-Indian-spices.jpg",
  },
  {
    id: "SWE009", category: "sweets", emoji: "🍬",
    name: { en: "Phali Dana- White (250 Gm)", hi: "Phali Dana- White (250 Gm)", ta: "Phali Dana- White (250 Gm)", te: "Phali Dana- White (250 Gm)" },
    desc: { en: "250 GM | Natural & Pure", hi: "250 GM | प्राकृतिक", ta: "250 GM | இயற்கையானது", te: "250 GM | సహజమైనది" },
    mrp: 45,
    wholesale: 40.37,
    unit: "250 GM",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Honey_in_bowl.jpg/320px-Honey_in_bowl.jpg",
  },
  {
    id: "SWE010", category: "sweets", emoji: "🍬",
    name: { en: "Phali Dana- Red (250 Gm)", hi: "Phali Dana- Red (250 Gm)", ta: "Phali Dana- Red (250 Gm)", te: "Phali Dana- Red (250 Gm)" },
    desc: { en: " | Natural & Pure", hi: " | प्राकृतिक", ta: " | இயற்கையானது", te: " | సహజమైనది" },
    mrp: 55,
    wholesale: 47.25,
    unit: "",
    stock: 100,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Honey_in_bowl.jpg/320px-Honey_in_bowl.jpg",
  },
];

function getPrice(product, customerType) {
  // customerType: "retail" or "wholesale"
  return customerType === "wholesale" ? product.wholesale : product.mrp;
}

function getCatalogText(lang, customerType = "retail") {
  return products.map(p => {
    const name  = p.name[lang] || p.name.en;
    const price = getPrice(p, customerType);
    return `${p.emoji} ${name} (${p.unit}) — ₹${price}`;
  }).join("\n");
}

function getProductById(id)           { return products.find(p => p.id === id); }
function getProductsByCategory(catId) { return products.filter(p => p.category === catId); }

const catalog = { store, categories, products };
module.exports = { catalog, store, products, categories, getProductById, getProductsByCategory, getCatalogText, getPrice };